package com.govindarajan.jtorrent.network;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.util.Arrays;

/**
 * Responsible for connecting to peer.
 */
public class PeerConnection {
    private final Peer peer;
    private final byte[] myPeerId;
    private final byte[] infoHash;
    private Socket socket;
    /**
     * Initializes a connection handler for a specific peer.
     * @param peer The remote peer to connect to.
     * @param peerID Our Client ID (generated by TrackerUtils).
     * @param infoHash The SHA-1 hash of the file we want to download.
     */
    public PeerConnection(Peer peer, byte[] peerID, byte[] infoHash){
        this.peer = peer;
        myPeerId = peerID;
        this.infoHash = infoHash;
    }

    /**
     * Creates a socket connection and sends handshake to the peer and validates the reponse handshake.
     * @throws IOException
     */
    public void connect() throws IOException {
        System.out.println("Connecting to "+ peer+"...");
        socket = new Socket(peer.getIp(), peer.getPort());
        socket.setSoTimeout(10000);

        OutputStream out = socket.getOutputStream();
        Handshake myHandshake = new Handshake(infoHash, myPeerId);
        out.write(myHandshake.getBytes());

        InputStream in = socket.getInputStream();
        byte[] response = in.readNBytes(68);
        if(response.length != 68)
            throw new IOException("Peer closed connection during handshake!");
        Handshake responseHandshake = Handshake.parse(response);
        if(!Arrays.equals(infoHash, responseHandshake.getInfoHash()))
            throw new IOException("Info hash mismatch! peer is sharing different info hash.");

        System.out.println("Handshake Successful! Connected to " + peer.getIp());
    }
}
